# tags is used to choose the runner, setup your own runner with gitlab-runner with the tag `deployPy`

before_script:
- python --version
- pip install pylint pytest # pyinstaller

image: "python:3.10"

stages:
- linting
- testing
# - deploy

# possible pylint detected errors:
# C0103: Argument name "x" doesn't conform to snake_case naming style
# C0114: Missing module docstring
# C0115: Missing class docstring
# C0116: Missing function or method docstring
# C0304: Final newline missing
# to skip this, change pylint script to: `pylint -d C0103,C0114,C0115,C0116,C0304 src/`
# already skipped inevitable pylint error bcuz idfk how to make it work either way

pylint:
  stage: linting
  only: 
  - merge_requests
  script: pylint -d E0401,E1101,W0212,C0413,R src/
  tags:
  - deployPy

pytest:
  stage: testing
  only: 
  - merge_requests
  script: cd src/tests/;pytest -v
  tags:
  - deployPy

# pyinstaller:
#   stage: deploy
#   only: 
#   - merge_requests
#   script: cd src/;pyinstaller -F --add-data "sqlscript/usada_carbon_tracker.sql;." dbhandler.py
#   tags:
#   - deployPy
#   artifacts:
#     paths: 
#       - src/dist/*.exe
